/// Villes proposées pour les fuseaux horaires : nom affiché et fuseau IANA,
/// relus par `WorldClockWidget.kt` sous la forme « Ville|Zone ».
const worldCities = <(String, String)>[
  ('Paris', 'Europe/Paris'),
  ('Londres', 'Europe/London'),
  ('Lisbonne', 'Europe/Lisbon'),
  ('Berlin', 'Europe/Berlin'),
  ('Athènes', 'Europe/Athens'),
  ('Moscou', 'Europe/Moscow'),
  ('Dubaï', 'Asia/Dubai'),
  ('Bombay', 'Asia/Kolkata'),
  ('Bangkok', 'Asia/Bangkok'),
  ('Singapour', 'Asia/Singapore'),
  ('Pékin', 'Asia/Shanghai'),
  ('Tokyo', 'Asia/Tokyo'),
  ('Séoul', 'Asia/Seoul'),
  ('Sydney', 'Australia/Sydney'),
  ('Auckland', 'Pacific/Auckland'),
  ('Honolulu', 'Pacific/Honolulu'),
  ('Los Angeles', 'America/Los_Angeles'),
  ('Denver', 'America/Denver'),
  ('Chicago', 'America/Chicago'),
  ('New York', 'America/New_York'),
  ('Montréal', 'America/Toronto'),
  ('Mexico', 'America/Mexico_City'),
  ('São Paulo', 'America/Sao_Paulo'),
  ('Buenos Aires', 'America/Argentina/Buenos_Aires'),
  ('Dakar', 'Africa/Dakar'),
  ('Casablanca', 'Africa/Casablanca'),
  ('Le Caire', 'Africa/Cairo'),
  ('Nairobi', 'Africa/Nairobi'),
  ('Johannesburg', 'Africa/Johannesburg'),
  ('Pointe-à-Pitre', 'America/Guadeloupe'),
  ('Saint-Denis (Réunion)', 'Indian/Reunion'),
  ('Nouméa', 'Pacific/Noumea'),
];
